package algorithm.java;

/**
 Given two strings s and t which consist of only lowercase letters.
 String t is generated by random shuffling string s and then add one more letter at a random position.
 Find the letter that was added in t.

 * Created by huaxiufeng on 19/3/23.
 */
public class LC389FindTheDifference {

    public char findTheDifference(String s, String t) {
        int[] count = new int[26];
        for (int i = 0; i < s.length(); i++) {
            ++count[s.charAt(i) - 'a'];
        }
        for (int i = 0; i < t.length(); i++) {
            if (--count[t.charAt(i) - 'a'] < 0) {
                return t.charAt(i);
            }
        }
        return 0;
    }

    public static void main(String[] args) {
        LC389FindTheDifference solution = new LC389FindTheDifference();
        System.out.println(solution.findTheDifference("abcd", "abcde")); // e
    }
}
